# Generated by Django 4.1.3 on 2022-12-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_alter_albumrated_image'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rated_albums',
            field=models.ManyToManyField(to='album.albumrated'),
        ),
    ]
