# Generated by Django 4.1.3 on 2022-11-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumRated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAlbum', models.CharField(max_length=255, unique=True)),
                ('Name', models.CharField(max_length=255)),
                ('Artist', models.CharField(max_length=255)),
                ('Image', models.CharField(max_length=255)),
                ('TotalTracks', models.IntegerField()),
            ],
        ),
    ]
