# Generated by Django 4.1.3 on 2022-11-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumrated',
            name='Rating',
            field=models.IntegerField(default=0),
        ),
    ]
