# Generated by Django 4.1.3 on 2022-12-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_alter_albumrated_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumrated',
            name='Image',
            field=models.CharField(max_length=255),
        ),
    ]
