# Generated by Django 4.1.3 on 2022-12-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_alter_albumrated_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumrated',
            name='idAlbum',
            field=models.CharField(max_length=255),
        ),
    ]
